export default [
  {
    "_id": "Q101",
    "title": "Rocket Propulsion Fundamentals Quiz",
    "description": "Test your knowledge of basic rocket propulsion concepts covered in the first two weeks.",
    "course": "RS101",
    "quizType": "GRADED_QUIZ",
    "points": 20,
    "assignmentGroup": "QUIZZES",
    "shuffleAnswers": true,
    "timeLimit": 30,
    "multipleAttempts": true,
    "attemptsAllowed": 99,
    "showCorrectAnswers": "AFTER_SUBMISSION",
    "accessCode": "",
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": "2026-02-15T23:59:00.000Z",
    "availableDate": "2023-02-01T08:00:00.000Z",
    "untilDate": "2026-02-15T23:59:00.000Z",
    "published": true,
    "creator": "faculty123"
  },
  {
    "_id": "Q102",
    "title": "Aerodynamics Midterm",
    "description": "Comprehensive assessment of aerodynamic principles and calculations.",
    "course": "RS102",
    "quizType": "GRADED_QUIZ",
    "points": 50,
    "assignmentGroup": "EXAMS",
    "shuffleAnswers": true,
    "timeLimit": 60,
    "multipleAttempts": false,
    "attemptsAllowed": 1,
    "showCorrectAnswers": "AFTER_DUE_DATE",
    "accessCode": "AERO2023",
    "oneQuestionAtATime": true,
    "webcamRequired": true,
    "lockQuestionsAfterAnswering": true,
    "dueDate": "2023-03-15T23:59:00.000Z",
    "availableDate": "2023-03-15T09:00:00.000Z",
    "untilDate": "2023-03-15T23:59:00.000Z",
    "published": false,
    "creator": "faculty123"
  },
  {
    "_id": "Q103",
    "title": "Organic Chemistry Practice Quiz",
    "description": "Practice quiz covering functional groups and basic reactions.",
    "course": "RS104",
    "quizType": "PRACTICE_QUIZ",
    "points": 10,
    "assignmentGroup": "QUIZZES",
    "shuffleAnswers": true,
    "timeLimit": 20,
    "multipleAttempts": true,
    "attemptsAllowed": 3,
    "showCorrectAnswers": "IMMEDIATELY",
    "accessCode": "",
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "dueDate": null,
    "availableDate": "2023-01-20T08:00:00.000Z",
    "untilDate": null,
    "published": true,
    "creator": "faculty123"
  }
]